APP_NAME: "eventmgr"
APP_PORT: "8002"

DB_DRIVER: "mongodb"
DB_HOST: "localhost"
DB_PORT: 27017
DB_NAME: "eventmgr"
DB_USER: ""
DB_PASSWORD: ""
DB_MAX_POOL_SIZE: 5
DB_MAX_OPEN_CONS: 5
DB_MAX_LIFE_TIME_MINS: 30
